config/routes.rb
PbdBiz::Application.routes.draw do
  resources :press_releases

  resources :books

  resources :publications

  root :to => "home#index"
  devise_for :users
end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :chapter_ranges
	has_many :page_ranges
end

app/models/chapter_range.rb
class ChapterRange < ResourceSection
end

app/models/page_range.rb
class PageRange < ResourceSection
end

app/models/press_release.rb
class PressRelease < ActiveRecord::Base
end

app/models/publication.rb
class Publication < ActiveRecord::Base
end

app/models/research_group.rb
class ResearchGroup < ActiveRecord::Base
  has_one :pi, class_name: "Scientist"
end

app/models/resource_section.rb
class ResourceSection < ActiveRecord::Base
end

app/models/scientist.rb
class Scientist < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :publisher, :editor_info, :edition, :isbn, :doi, :abstract, :published_at)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/press_releases_controller.rb
class PressReleasesController < ApplicationController
  before_action :set_press_release, only: [:show, :edit, :update, :destroy]

  # GET /press_releases
  # GET /press_releases.json
  def index
    @press_releases = PressRelease.all
  end

  # GET /press_releases/1
  # GET /press_releases/1.json
  def show
  end

  # GET /press_releases/new
  def new
    @press_release = PressRelease.new
  end

  # GET /press_releases/1/edit
  def edit
  end

  # POST /press_releases
  # POST /press_releases.json
  def create
    @press_release = PressRelease.new(press_release_params)

    respond_to do |format|
      if @press_release.save
        format.html { redirect_to @press_release, notice: 'Press release was successfully created.' }
        format.json { render action: 'show', status: :created, location: @press_release }
      else
        format.html { render action: 'new' }
        format.json { render json: @press_release.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /press_releases/1
  # PATCH/PUT /press_releases/1.json
  def update
    respond_to do |format|
      if @press_release.update(press_release_params)
        format.html { redirect_to @press_release, notice: 'Press release was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @press_release.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /press_releases/1
  # DELETE /press_releases/1.json
  def destroy
    @press_release.destroy
    respond_to do |format|
      format.html { redirect_to press_releases_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_press_release
      @press_release = PressRelease.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def press_release_params
      params.require(:press_release).permit(:media_type, :media_name, :url, :published_at, :abstract)
    end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render action: 'show', status: :created, location: @publication }
      else
        format.html { render action: 'new' }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:title, :journal_name, :journal_url, :pages, :volume, :issue, :published_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/press_releases_helper.rb
module PressReleasesHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/books/_form.html.erb
<%= form_for(@book, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @book.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h4>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :publisher, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :publisher, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :editor_info, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :editor_info, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :edition, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :edition, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :isbn, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :isbn, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :doi, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :doi, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :abstract, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :abstract, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :published_at, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.datetime_select :published_at, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="page-header">
  <%= link_to books_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @book, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing book</h1>
</div>

<%= render 'form' %>

app/views/books/index.html.erb
<div class="page-header">
  <%= link_to new_book_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Book
  <% end %>
  <h1>Listing books</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Publisher</th>
            <th>Editor info</th>
            <th>Edition</th>
            <th>Isbn</th>
            <th>Doi</th>
            <th>Abstract</th>
            <th>Published at</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @books) do |book| %>
            <td><%= book.title %></td>
            <td><%= book.publisher %></td>
            <td><%= book.editor_info %></td>
            <td><%= book.edition %></td>
            <td><%= book.isbn %></td>
            <td><%= book.doi %></td>
            <td><%= book.abstract %></td>
            <td><%= book.published_at %></td>
            <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/new.html.erb
<div class="page-header">
  <%= link_to books_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New book</h1>
</div>

<%= render 'form' %>

app/views/books/show.html.erb
<div class="page-header">
  <%= link_to books_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_book_path(@book), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show book</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @book.title %></dd>

  <dt>Publisher:</dt>
  <dd><%= @book.publisher %></dd>

  <dt>Editor info:</dt>
  <dd><%= @book.editor_info %></dd>

  <dt>Edition:</dt>
  <dd><%= @book.edition %></dd>

  <dt>Isbn:</dt>
  <dd><%= @book.isbn %></dd>

  <dt>Doi:</dt>
  <dd><%= @book.doi %></dd>

  <dt>Abstract:</dt>
  <dd><%= @book.abstract %></dd>

  <dt>Published at:</dt>
  <dd><%= @book.published_at %></dd>

</dl>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "PBD Admin", "/", :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="/">Home</a>
        </li>
        <li>
          <%= link_to "Publications", publications_path %>
        </li>
        <li>
          <%= link_to "Books", books_path %>
        </li>
      <% if user_signed_in? %>
        <li>
          <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Login', new_user_session_path %>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li>
          <%= link_to 'Edit account', edit_user_registration_path %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Sign up', new_user_registration_path %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>PBD Admin</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
</head>
<body>

  <div class="container">
    <%= render "layouts/messages" %>
    <%= render "layouts/navigation" %>
    <%= yield %>
  </div>

<!-- HTML5 shim and Respond.js IE8 support of HTML5 and media queries -->
<!--[if lt IE 9]>
  <%= javascript_include_tag "bootstrap-ie" %>
<![endif]-->
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/press_releases/_form.html.erb
<%= form_for(@press_release, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @press_release.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@press_release.errors.count, "error") %> prohibited this press_release from being saved:</h4>

      <ul>
      <% @press_release.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :media_type, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :media_type, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :media_name, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :media_name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :url, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :published_at, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.datetime_select :published_at, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :abstract, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :abstract, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/press_releases/edit.html.erb
<div class="page-header">
  <%= link_to press_releases_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @press_release, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing press_release</h1>
</div>

<%= render 'form' %>

app/views/press_releases/index.html.erb
<div class="page-header">
  <%= link_to new_press_release_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Press release
  <% end %>
  <h1>Listing press_releases</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Media type</th>
            <th>Media name</th>
            <th>Url</th>
            <th>Published at</th>
            <th>Abstract</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @press_releases) do |press_release| %>
            <td><%= press_release.media_type %></td>
            <td><%= press_release.media_name %></td>
            <td><%= press_release.url %></td>
            <td><%= press_release.published_at %></td>
            <td><%= press_release.abstract %></td>
            <td><%= link_to 'Show', press_release %></td>
        <td><%= link_to 'Edit', edit_press_release_path(press_release) %></td>
        <td><%= link_to 'Destroy', press_release, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/press_releases/new.html.erb
<div class="page-header">
  <%= link_to press_releases_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New press_release</h1>
</div>

<%= render 'form' %>

app/views/press_releases/show.html.erb
<div class="page-header">
  <%= link_to press_releases_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_press_release_path(@press_release), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show press_release</h1>
</div>

<dl class="dl-horizontal">
  <dt>Media type:</dt>
  <dd><%= @press_release.media_type %></dd>

  <dt>Media name:</dt>
  <dd><%= @press_release.media_name %></dd>

  <dt>Url:</dt>
  <dd><%= @press_release.url %></dd>

  <dt>Published at:</dt>
  <dd><%= @press_release.published_at %></dd>

  <dt>Abstract:</dt>
  <dd><%= @press_release.abstract %></dd>

</dl>

app/views/publications/_form.html.erb
<%= form_for(@publication, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @publication.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h4>

      <ul>
      <% @publication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :journal_name, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :journal_name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :journal_url, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :journal_url, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :pages, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :pages, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :volume, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.number_field :volume, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :issue, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.number_field :issue, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :published_at, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.datetime_select :published_at, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/publications/edit.html.erb
<div class="page-header">
  <%= link_to publications_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @publication, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing publication</h1>
</div>

<%= render 'form' %>

app/views/publications/index.html.erb
<div class="page-header">
  <%= link_to new_publication_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Publication
  <% end %>
  <h1>Listing publications</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Journal name</th>
            <th>Journal url</th>
            <th>Pages</th>
            <th>Volume</th>
            <th>Issue</th>
            <th>Published at</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @publications) do |publication| %>
            <td><%= publication.title %></td>
            <td><%= publication.journal_name %></td>
            <td><%= publication.journal_url %></td>
            <td><%= publication.pages %></td>
            <td><%= publication.volume %></td>
            <td><%= publication.issue %></td>
            <td><%= publication.published_at %></td>
            <td><%= link_to 'Show', publication %></td>
        <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
        <td><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/publications/new.html.erb
<div class="page-header">
  <%= link_to publications_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New publication</h1>
</div>

<%= render 'form' %>

app/views/publications/show.html.erb
<div class="page-header">
  <%= link_to publications_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_publication_path(@publication), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show publication</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @publication.title %></dd>

  <dt>Journal name:</dt>
  <dd><%= @publication.journal_name %></dd>

  <dt>Journal url:</dt>
  <dd><%= @publication.journal_url %></dd>

  <dt>Pages:</dt>
  <dd><%= @publication.pages %></dd>

  <dt>Volume:</dt>
  <dd><%= @publication.volume %></dd>

  <dt>Issue:</dt>
  <dd><%= @publication.issue %></dd>

  <dt>Published at:</dt>
  <dd><%= @publication.published_at %></dd>

</dl>